name: release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  release:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH: gh-pages
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name:
      run: |
        tmpdir=$(mktemp -d /tmp/foo.XXXXXX)
        cp *.html *.js *.txt ${tmpdir} || true
        git checkout ${RELEASE_BRANCH}
        rm -rf *
        cp ${tmpdir}/* .

        # https://docs.github.com/en/enterprise-server@3.2/actions/learn-github-actions/environment-variables#default-environment-variables
        cat<<EOF>version.txt
        git sha: #${GITHUB_SHA:0:7}
        git tag: #$(basename ${GITHUB_REF})
        date: $(date)
        EOF

        git config user.email "noone@example.com"
        git config user.name "Release Bot"

        git add .
        git commit -m "Tag #$(basename ${GITHUB_REF}), Sha #${GITHUB_SHA:0:7}"
        git push origin gh-pages

